#!/bin/bash

if [ -z "$WASI_SDK_PATH" ]; then
  echo "WASI_SDK_PATH is not set" >&2
  exit 1
fi

{
  echo "WASI_SDK_PATH: $WASI_SDK_PATH"
} >&2


RUBY_SOURCE_DIR="$(cd "$(dirname "$0")/ruby" && pwd)"

echo "RUBY_SOURCE_DIR: $RUBY_SOURCE_DIR"

"$RUBY_SOURCE_DIR/configure" \
  --host wasm32-unknown-wasi --with-destdir=./ruby-wasm32-wasi --disable-install-doc \
  --with-ext="bigdecimal,cgi/escape,continuation,coverage,date,dbm,digest/bubblebabble,digest,digest/md5,digest/rmd160,digest/sha1,digest/sha2,etc,fcntl,fiber,gdbm,json,json/generator,json/parser,nkf,objspace,pathname,racc/cparse,rbconfig/sizeof,ripper,stringio,strscan,monitor" \
  LDFLAGS="-Xlinker --stack-first -Xlinker -z -Xlinker stack-size=16777216" \
  CFLAGS="-fPIC -fvisibility=default" \
  XLDFLAGS="-Xlinker -shared -Xlinker --export-dynamic -Xlinker --export-all -Xlinker --experimental-pic -Xlinker -export-if-defined=__main_argc_argv" \
  optflags="-O2" \
  debugflags="" \
  wasmoptflags="-O2"
